import fs from "node:fs/promises";
import { config, connectorStatus } from "../config.mjs";

async function refreshYouTubeAccessToken() {
  const params = new URLSearchParams({
    client_id: config.platforms.youtube.clientId,
    client_secret: config.platforms.youtube.clientSecret,
    refresh_token: config.platforms.youtube.refreshToken,
    grant_type: "refresh_token",
  });
  const response = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: params,
  });
  if (!response.ok) throw new Error(`YouTube token refresh failed: ${await response.text()}`);
  const data = await response.json();
  return data.access_token;
}

async function publishYouTube({ videoPath, title, description }) {
  const accessToken = await refreshYouTubeAccessToken();
  const metadata = {
    snippet: {
      title: title.slice(0, 95),
      description,
      categoryId: "24",
    },
    status: {
      privacyStatus: config.platforms.youtube.privacyStatus,
      selfDeclaredMadeForKids: false,
    },
  };

  const init = await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status", {
    method: "POST",
    headers: {
      authorization: `Bearer ${accessToken}`,
      "content-type": "application/json; charset=UTF-8",
      "x-upload-content-type": "video/mp4",
    },
    body: JSON.stringify(metadata),
  });
  if (!init.ok) throw new Error(`YouTube upload init failed: ${await init.text()}`);
  const uploadUrl = init.headers.get("location");
  const video = await fs.readFile(videoPath);
  const upload = await fetch(uploadUrl, {
    method: "PUT",
    headers: {
      authorization: `Bearer ${accessToken}`,
      "content-type": "video/mp4",
      "content-length": String(video.length),
    },
    body: video,
  });
  if (!upload.ok) throw new Error(`YouTube upload failed: ${await upload.text()}`);
  const data = await upload.json();
  return { platform_post_id: data.id, url: `https://youtube.com/watch?v=${data.id}`, raw: data };
}

async function publishTelegram({ videoPath, title, description }) {
  const form = new FormData();
  form.append("chat_id", config.platforms.telegram.chatId);
  form.append("caption", `${title}\n\n${description}`.slice(0, 1024));
  const buffer = await fs.readFile(videoPath);
  form.append("video", new Blob([buffer], { type: "video/mp4" }), "viralforge.mp4");
  const response = await fetch(`https://api.telegram.org/bot${config.platforms.telegram.botToken}/sendVideo`, {
    method: "POST",
    body: form,
  });
  if (!response.ok) throw new Error(`Telegram publish failed: ${await response.text()}`);
  const data = await response.json();
  return {
    platform_post_id: String(data.result?.message_id || ""),
    url: "",
    raw: data,
  };
}

export async function distribute({ repo, run, content, videoAsset }) {
  const statuses = connectorStatus();
  const platforms = run.input.platforms || ["YouTube", "TikTok", "Instagram", "X", "LinkedIn", "Pinterest", "Reddit", "Telegram"];
  const posts = [];
  const title = content.brief?.title || run.input.topic || "ViralForge content";
  const description = content.brief?.hook || "Generated by ViralForge.";
  const localVideoPath = videoAsset.uri.startsWith("s3://") || videoAsset.uri.startsWith("http") ? null : videoAsset.uri;

  for (const platform of platforms) {
    const status = statuses[platform] || "connector_not_configured";
    const liveAllowed = config.app.publishMode === "live";
    try {
      if (liveAllowed && platform === "YouTube" && status.startsWith("ready") && localVideoPath) {
        const result = await publishYouTube({ videoPath: localVideoPath, title, description });
        posts.push(await repo.addPost({
          run_id: run.id,
          content_id: content.id,
          platform,
          status: "published",
          platform_post_id: result.platform_post_id,
          url: result.url,
          metadata: { connectorStatus: status, result },
        }));
      } else if (liveAllowed && platform === "Telegram" && status.startsWith("ready") && localVideoPath) {
        const result = await publishTelegram({ videoPath: localVideoPath, title, description });
        posts.push(await repo.addPost({
          run_id: run.id,
          content_id: content.id,
          platform,
          status: "published",
          platform_post_id: result.platform_post_id,
          url: result.url,
          metadata: { connectorStatus: status, result },
        }));
      } else {
        posts.push(await repo.addPost({
          run_id: run.id,
          content_id: content.id,
          platform,
          status: liveAllowed ? "blocked_connector_not_ready" : "export_ready",
          metadata: {
            connectorStatus: status,
            publishMode: config.app.publishMode,
            package: {
              title,
              description,
              aiGenerated: true,
              videoUri: videoAsset.uri,
            },
          },
        }));
      }
    } catch (error) {
      posts.push(await repo.addPost({
        run_id: run.id,
        content_id: content.id,
        platform,
        status: "failed",
        metadata: { connectorStatus: status, error: error.message },
      }));
    }
  }

  return posts;
}
