import fs from "node:fs/promises";
import path from "node:path";
import { config } from "../config.mjs";
import { runFfmpeg } from "../runtime/ffmpeg.mjs";

function splitLines(text, maxLength = 22, maxLines = 4) {
  const words = String(text || "ViralForge").replace(/\s+/g, " ").trim().split(" ");
  const lines = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxLength && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
    if (lines.length === maxLines - 1) break;
  }
  if (current) lines.push(current);
  return lines.slice(0, maxLines);
}

function localAssetPath(asset) {
  const uri = asset?.uri || "";
  return uri && !uri.startsWith("http") && !uri.startsWith("s3://") ? uri : null;
}

function ffmpegTextPath(filePath) {
  return filePath.replaceAll("\\", "/").replaceAll(":", "\\:").replaceAll("'", "\\'");
}

export async function renderTemplateVideo({ storage, runId, title, script, assets = [], durationSeconds = 10 }) {
  const scratch = path.join(config.app.dataDir, "scratch", runId);
  await fs.mkdir(scratch, { recursive: true });
  const output = path.join(scratch, "viralforge.mp4");
  const titleLines = splitLines(title, 24, 4);
  const hook = script?.voiceover?.[0] || script?.scenes?.[0]?.overlay || "Generated by ViralForge";
  const hookLines = splitLines(hook, 34, 3);
  const audioPath = localAssetPath(assets.find(asset => asset.type === "audio"));

  const textFilters = [];
  for (const [index, line] of titleLines.entries()) {
    const file = path.join(scratch, `title-${index}.txt`);
    await fs.writeFile(file, line);
    textFilters.push(`drawtext=textfile='${ffmpegTextPath(file)}':fontcolor=white:fontsize=54:font=Arial:x=72:y=${250 + index * 70}:borderw=2:bordercolor=0x10111f@0.35`);
  }
  for (const [index, line] of hookLines.entries()) {
    const file = path.join(scratch, `hook-${index}.txt`);
    await fs.writeFile(file, line);
    textFilters.push(`drawtext=textfile='${ffmpegTextPath(file)}':fontcolor=white:fontsize=30:font=Arial:x=72:y=${760 + index * 44}:borderw=2:bordercolor=0x10111f@0.35`);
  }
  const filter = [
    "drawbox=x=0:y=0:w=720:h=1280:color=0x9b0ae8@0.42:t=fill",
    "drawbox=x=0:y=770:w=720:h=510:color=0xed3782@0.36:t=fill",
    "drawbox=x=56:y=190:w=608:h=890:color=0xffffff@0.10:t=fill",
    "drawtext=text='ViralForge':fontcolor=white:fontsize=38:font=Arial:x=72:y=130",
    "drawtext=text='AI MEDIA ENGINE':fontcolor=0xFEFBFE:fontsize=22:font=Arial:x=72:y=1140",
    ...textFilters,
  ].join(",");

  const args = [
    "-y",
    "-f", "lavfi",
    "-i", `color=c=0x10111f:s=720x1280:d=${durationSeconds}`,
  ];
  if (audioPath) {
    args.push("-i", audioPath);
  } else {
    args.push("-f", "lavfi", "-i", `sine=frequency=420:duration=${durationSeconds}`);
  }
  args.push(
    "-filter_complex",
    filter,
    "-shortest",
    "-t", String(durationSeconds),
    "-pix_fmt", "yuv420p",
    "-c:v", "libx264",
    "-c:a", "aac",
    "-movflags", "+faststart",
    output,
  );

  await runFfmpeg(args, { requireDrawtext: true });

  const stored = await storage.putBuffer(`runs/${runId}/video.mp4`, await fs.readFile(output), "video/mp4");
  return {
    ...stored,
    title,
    durationSeconds,
    renderPath: "ffmpeg_template",
    aspectRatio: "9:16",
  };
}
